### ISSUE TITLE
Broken with non-local firebase-app

### ISSUE THREAD

**Issue by arjunyel** [convoo/file-fire#8]
```
<firebase-app
        name="camp"
        auth-domain="blahblahblah"
        database-url="blahblahblah.com"
        api-key="blahblahblah"
        storage-bucket="blahblahblah.appspot.com">
    </firebase-app>
<file-fire
          id="upload"
          app-name="camp"
          progress="{{progress}}"
          download-url="{{downloadUrl}}"
          path="/[[user.uuid]]/picture"></file-fire>
```

Gets error in console: "Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)."
name:"[DEFAULT]"
stack:
"FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).↵    at o (http://localhost:8081/bower_components/firebase/firebase-app.js:5:4732)↵    at Object.e [as app] (http://localhost:8081/bower_components/firebase/firebase-app.js:5:3153)↵    at HTMLElement.<anonymous> (http://localhost:8081/bower_components/file-fire/file-fire-behavior.html:381:47)↵    at Promise (<anonymous>)↵    at HTMLElement._uploadThis (http://localhost:8081/bower_components/file-fire/file-fire-behavior.html:377:12)↵    at HTMLElement._uploadNext (http://localhost:8081/bower_components/file-fire/file-fire-behavior.html:365:19)↵    at HTMLElement._upload (http://localhost:8081/bower_components/file-fire/file-fire-behavior.html:244:17)↵    at <anonymous>"

**Comment by sbeleidy** [comment]
Thanks for reporting this @arjunyel!

Error also appears at https://www.webcomponents.org/preview/convoo/file-fire/1ebc23fad6e0a891e5f8cb3387225e4e4a4eb66d in the console. 

We need to determine whether this is an issue on our end or polymerfire.
